-- USERS
create table public.users (
  id uuid references auth.users not null primary key,
  full_name text,
  avatar_url text
);
alter table public.users enable row level security;
create policy "Allow view own user data" on public.users for select using (auth.uid() = id);
create policy "Allow update own user data" on public.users for update using (auth.uid() = id);

/**
* This trigger automatically creates a user entry when a new user signs up via Supabase Auth.
*/ 
create function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.users (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ROOMS
create table public.rooms (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  slug          text not null unique,
  name          text,
  owner_id      uuid references public.users
  locked        boolean default false not null
);
alter table public.rooms enable row level security;
create policy "Allow public view" on public.rooms for select using (true);
create policy "Allow individual insert access" on public.rooms for insert with check (auth.uid() = owner_id);
create policy "Allow owner update access" on public.rooms for update using (auth.uid() = owner_id);
create policy "Allow owner delete access" on public.rooms for delete using (auth.uid() = owner_id);

-- MESSAGES
create table public.messages (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  message       text not null,
  identity      text not null,
  user_id       uuid references public.users,
  room_id       bigint references public.rooms not null
);
alter table public.messages enable row level security;
create policy "Allow read own messages access" on public.messages for select using ( auth.uid() = 'user_id' );
create policy "Allow individual insert access" on public.messages for insert with check ( auth.uid() = user_id );
